apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservice
spec:
  selector:
    matchLabels:
      app: orderservice
  replicas: 3
  template:
    metadata:
      labels:
        app: orderservice
    spec:
      containers:
        - name: orderservice
          image: docker.io/sanduni98/docker-abc-order:v1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080