apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
spec:
  selector:
    matchLabels:
      app: userservice
  replicas: 3
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
        - name: userservice
          image: docker.io/dockerdana800433/it19168364:v1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5003