apiVersion: v1
kind: Service
metadata: 
  name: item-handling-service
spec:
  selector:
    app: itemhandlingservice
  ports:
    - protocol: "TCP"
      port: 5003
      targetPort: 5003
  type: LoadBalancer 