apiVersion: v1
kind: Service
metadata: 
  name: item-handling-service
spec:
  selector:
    app: itemhandlingservice
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: LoadBalancer 